### ISSUE TITLE
docker pull not working

### ISSUE THREAD

**Issue by jroxendal** [amake/moses-docker#1]
Just a heads up: I got an error when pulling from docker hub:
```
docker pull amake/moses-smt
Using default tag: latest
Error response from daemon: manifest for amake/moses-smt:latest not found
```

I just rebuilt locally, works like a dream! Thanks for this repo, you saved me a million hours of tedium 🥇

**Comment by amake** [comment]
I'm glad you found the repo useful.

Pulling `amake/moses-smt` defaults to the `latest` tag, but the image is on the `base` tag, so you need to do `docker pull amake/moses-smt:base`.
