### ISSUE TITLE
Segmentation fault. Decoder died

### ISSUE THREAD

**Issue by AlAntonov** [amake/moses-docker#3]
Hi, amake. Great docker! Thanks for it.

I have some issues with decoder.

Finally i've localized my problem as follows:
Using phrase-model from http://www.statmt.org/moses/?n=Moses.Tutorial

```
wget http://www.statmt.org/moses/download/sample-models.tgz
tar zxvf sample-models.tgz
/opt/bin/moses/bin/moses -f phrase-model/moses.ini
```

i am getting 

```
Reading phrase-model/phrase-table
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Created input-output object : [0.692] seconds
hi
Translating: hi
Line 0: Initialize search took 0.000 seconds total
Line 0: Collecting options took 0.000 seconds at moses/Manager.cpp Line 141
Line 0: Search took 0.000 seconds
Segmentation fault
```

Actually i have the same error with my trained model too. Could you please advice?

**Comment by amake** [comment]
Sorry, I can't help with issues with Moses itself. Please try their mailing list:
http://www.statmt.org/moses/?n=Moses.MailingLists

**Comment by AlAntonov** [comment]
Thank you anyway. I will try to figure it out
